#pragma once
#include "CoreMinimal.h"
#include "EDamageSource.generated.h"

UENUM(BlueprintType)
enum class EDamageSource : uint8 {
    None,
    AnomalyStrike,
    Bullet,
    ShockWave,
    Explosion,
    BiteSmall,
    BiteLarge,
    CutSmall,
    CutLarge,
    RamSmall,
    RamLarge,
    Knife,
    WeaponButt,
    Fire,
    Electricity,
    ElectricityPermanent,
    Acid,
    Radiation,
    PSY,
    Bleeding,
    Emission,
    Physics,
    Hunger,
    BulletHeavy,
    Buckshot,
    Chemical,
    Expulsion,
    ClassicFire,
    SoapBubble,
    Diamond,
    IronWind,
    Carousel,
    LightningBall,
    LavaLamp,
    ToxicCloud,
    Clicker,
    Bulb,
    FireBreath,
    WanderingLights,
    PoppyField,
    PoltergeistCommonCollisionAttack,
    PoltergeistFireCollisionAttack,
    PoltergeistElectroCollisionAttack,
    PoltergeistChemicalCollisionAttack,
    Water,
    Fall,
    StealthKill,
    CommonPermanent,
    GetCount,
};

