#pragma once
#include "CoreMinimal.h"
#include "EPhysicalMaterialType.generated.h"

UENUM()
enum class EPhysicalMaterialType : int32 {
    Default,
    Dirt,
    Grass,
    Brick,
    Glass,
    Sand,
    Rock,
    Asphalt,
    Cloth,
    Leather,
    Rubber,
    Paper,
    Plastic,
    Flesh,
    FleshCloth,
    FleshMetal,
    FleshRubber,
    WoodThin,
    WoodSolid,
    MetalThin,
    MetalSolid,
    MetalGrid,
    Slate,
    Water,
    Chemical,
    Bread,
    Meat,
    Vegetable,
    Tree,
    ForestGrass,
    Puddle,
    Gravel,
    BrokenGlass,
    Ground,
    ForestPine,
    Artifact,
    Leaves,
    Ceramic,
    TreeNoParticles,
    GlassNoParticles,
    Bone,
    ClothCorpses,
    FleshCorpses,
    ArmoredGlass,
    AirPoltergeist,
    FaustInvulnerable,
    GetCount,
};

