#pragma once
#include "CoreMinimal.h"
#include "EQuestConditionType.generated.h"

UENUM(BlueprintType)
enum class EQuestConditionType : uint8 {
    HP,
    HPPercent,
    Stamina,
    Radiation,
    Bleeding,
    Psy,
    HungerPoints,
    Money,
    InventoryWeight,
    IsAlive,
    IsOnline,
    FactionRelationship,
    PersonalRelationship,
    Rank,
    Effect,
    Awareness,
    Note,
    ItemInInventory,
    AITarget,
    GlobalVariable,
    Trigger,
    DistanceToNPC,
    DistanceToPoint,
    LookAtAngle,
    Bridge,
    ItemInContainer,
    EquipmentInHands,
    IsAiming,
    CorpseCarry,
    JournalState,
    IsCreated,
    Emission,
    PlayerOverload,
    IsWounded,
    ContextualAction,
    IsDialogMemberValid,
    Weather,
    IsEnoughAmmo,
    IsWeaponJammed,
    HasItemInQuickSlot,
    ArmorState,
    Random,
    FastTravelMoney,
    NodeState,
    Last = 255,
};

